### ISSUE TITLE
Implement Feature to Fetch Economic Data from FRED API and Store in SQLite Database

### ISSUE THREAD

**Issue by espin086** [espin086/NewsWaveMetrics#2]
Summary
We require the development of a feature to fetch economic data using the FRED (Federal Reserve Economic Data) API and store this data in a SQLite database. The data will be stored in a new table named fred and should include a range of economic indicators with varying frequencies (daily, weekly, or monthly).

Detailed Description
This feature aims to automate the retrieval of economic indicators from the FRED API, focusing on metrics such as Exchange Rates, Treasury yields, the Fed Funds Rate, CPI, GDP, and more. The data collected will support financial analysis, economic research, and modeling within our application.

Requirements:

Data Fields: Fetch the following economic indicators, prioritizing daily data, but falling back to weekly or monthly frequencies if daily data is not available:
Exchange Rates
2 Year Treasury
10 Year Treasury
Fed Funds Rate
CPI (Consumer Price Index)
GDP (Gross Domestic Product)
Industrial Production
Employment
Consumer Sentiment
PPI (Producer Price Index)
Any additional economic  LEADING indicators listed on the [Wikipedia page for Economic Indicators](https://en.wikipedia.org/wiki/Economic_indicator).
Database Schema: Create a new table named fred in our existing SQLite database. The table should have columns for each of the metrics listed above, along with columns for the date and frequency of the data.
FRED API Integration: Utilize the FRED API to fetch the required economic data. Ensure to handle API authentication, rate limits, and data normalization.
Data Update Frequency: Implement a mechanism to regularly update the database with the latest available data for each indicator, considering their respective frequencies.
Error Handling: Implement comprehensive error handling for API connectivity issues, data parsing errors, and database insertion failures.
Documentation: Provide detailed documentation on how to configure the FRED API (including obtaining and setting up API keys) and how to operate the data fetching and storage feature.
Acceptance Criteria
The system can fetch and store the specified economic indicators from the FRED API into the fred table in the SQLite database.
Data is updated according to its availability frequency, with fallbacks to less frequent data if daily data is not available.
Proper error handling and logging are in place for troubleshooting.
Documentation is complete and clear, enabling easy setup and maintenance of the feature.

**Comment by ZaibyS** [comment]
@espin086 
Today, I conducted research on the FRED API and identified the following datasets relevant to the metrics mentioned:
1. **Exchange Rates**
   - [Nominal Broad U.S. Dollar Index (Daily)](https://fred.stlouisfed.org/series/DTWEXBGS)
2. **Treasury Yields**
   - [10-Year Treasury Constant Maturity Minus 2-Year Treasury Constant Maturity (Daily)](https://fred.stlouisfed.org/series/T10Y2Y)
3. **Fed Funds Rate**
   - [Federal Funds Effective Rate (Daily)](https://fred.stlouisfed.org/series/DFF)
4. **CPI (Consumer Price Index)**
   - [Consumer Price Index for All Urban Consumers: All Items in U.S. City Average (Monthly)](https://fred.stlouisfed.org/series/CPIAUCSL)
   - [Median Consumer Price Index (Monthly)](https://fred.stlouisfed.org/series/MEDCPIM158SFRBCLE)
5. **GDP (Gross Domestic Product)**
   - [Gross Domestic Product (Quarterly)](https://fred.stlouisfed.org/series/GDP)
6. **Industrial Production**
   - [Industrial Production: Total Index (Monthly)](https://fred.stlouisfed.org/series/INDPRO)
7. **Employment**
   - [All Employees, Total Nonfarm (Monthly)](https://fred.stlouisfed.org/series/PAYEMS)
   - [Employment-Population Ratio (Monthly)](https://fred.stlouisfed.org/series/EMRATIO)
8. **Unemployment Rate**
   - [Unemployment Rate (Monthly)](https://fred.stlouisfed.org/series/UNRATE)
9. **Consumer Sentiment**
   - [University of Michigan: Consumer Sentiment (Monthly)](https://fred.stlouisfed.org/series/UMCSENT)
10. **PPI (Producer Price Index)**
    - [Producer Price Index by Commodity: All Commodities (Monthly)](https://fred.stlouisfed.org/series/PPIACO)
    
Do you find these datasets suitable for use? Additionally, for CPI and Employment metrics, which dataset should we prioritize?

**Comment by espin086** [comment]
for CPI please use: [Consumer Price Index for All Urban Consumers: All Items in U.S. City Average (Monthly)](https://fred.stlouisfed.org/series/CPIAUCSL) 

for employment please use:  https://fred.stlouisfed.org/series/UNRATE/, just use the unemployment rate, that’s easier, so just ignore the other two you have

**Comment by espin086** [comment]
In terms of prioritizing, please get the daily metrics first, then the monthly then all others after that

So for example the Exchange rate is daily so pull that in before you pull in unemployment which is monthl

So prioritize the data that comes in more frequently
